FROM apache/airflow:2.10.4

# USER root
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     libpq-dev gcc python3-dev \
#     && rm -rf /var/lib/apt/lists/*

# COPY requirements.txt /opt/airflow/scripts/requirements.txt

# USER airflow
# RUN pip install --no-cache-dir -r /opt/airflow/scripts/requirements.txt