services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis-volume:/data
    networks:
      - redis_apps_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s

volumes:
  redis-volume:
    name: redis-volume

networks:
  redis_apps_network:
    driver: bridge
    name: apps_network
    external: true
