services:
  postgres:
    image: library/postgres:14
    container_name: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: preprod_db
    ports:
      - '5432:5432'
    restart: always
    networks:
      - p_apps_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pdadmin4
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - p_apps_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s
  
volumes:
  postgres-volume:
  pgadmin-volume:

networks:
  p_apps_network:
    driver: bridge
    name: apps_network
    external: true
