services:
  postgres:
    image: library/postgres:latest
    container_name: postgres
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - path: ./.env
        required: true
    ports:
      - '5432:5432'
    restart: always
    networks:
      - p_apps_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "super_user", "-d", "telegram_bot_db"]
      interval: 10s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pdadmin4
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    ports:
      - '5050:80'
    env_file:
      - path: ./.env
        required: true
    depends_on:
      - postgres
    networks:
      - p_apps_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s
  
volumes:
  postgres-volume:
    name: postgres-volume
  pgadmin-volume:
    name: pgadmin-volume

networks:
  p_apps_network:
    driver: bridge
    name: apps_network
    external: true
